return {
    -- {
    --     "saghen/blink.cmp",
    --     opts = function(_, opts)
    --         opts.keymap = "super-tab"
    --
    --         opts.kind_icons = {
    --             Text = "󰉿",
    --             Method = "󰊕",
    --             Function = "󰊕",
    --             Constructor = "󰒓",
    --
    --             Field = "󰜢",
    --             Variable = "󰆦",
    --             Property = "󰖷",
    --
    --             Class = "󱡠",
    --             Interface = "󱡠",
    --             Struct = "󱡠",
    --             Module = "󰅩",
    --
    --             Unit = "󰪚",
    --             Value = "󰦨",
    --             Enum = "󰦨",
    --             EnumMember = "󰦨",
    --
    --             Keyword = "󰻾",
    --             Constant = "󰏿",
    --
    --             Snippet = "󱄽",
    --             Color = "󰏘",
    --             File = "󰈔",
    --             Reference = "󰬲",
    --             Folder = "󰉋",
    --             Event = "󱐋",
    --             Operator = "󰪚",
    --             TypeParameter = "󰬛",
    --         }
    --
    --         opts.accept = {
    --             expand_snippet = require("luasnip").lsp_expand,
    --         }
    --
    --         opts.sources = {
    --             completion = {
    --                 enabled_providers = {
    --                     "lsp",
    --                     "path",
    --                     "snippets",
    --                     "buffer",
    --                 },
    --             },
    --
    --             snippets = {
    --                 name = "LuaSnip",
    --                 friendly_snippets = false,
    --                 opts = {
    --                     search_paths = {
    --                         "~/.config/nvim/LuaSnip/",
    --                     },
    --                 },
    --             },
    --         }
    --     end,
    -- },
}
