general.import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]
general.live_config_reload = true

[font]
size = 15.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window]
decorations = "None"
option_as_alt = "Both"

[keyboard]
bindings = [
  { key = "=", mods = "Command", action = "IncreaseFontSize" },
  { key = "-", mods = "Command", action = "DecreaseFontSize" },
  { key = "0", mods = "Command", action = "ResetFontSize" },
]

[mouse]
hide_when_typing = true

[cursor]
style = { shape = "Block", blinking = "Off" }
